mod accept_contract;
mod agent;
mod cargo;
mod contract;
mod dock;
mod extract;
mod faction;
mod get_rate_limit;
mod market;
mod navigate;
mod orbit;
mod purchase_ship;
mod query;
mod refuel;
mod register;
mod request_not_cloned_error;
mod sell;
mod ship;
mod shipyard;
mod status;
mod status_error;
mod system;
mod too_many_retries_error;
mod waypoint;

pub use accept_contract::accept_contract;
pub use agent::agent;
pub use cargo::cargo;
pub use contract::contract;
pub use contract::contracts;
pub use contract::contracts_page;
pub use dock::dock;
pub use extract::extract;
pub use faction::faction;
pub use faction::factions;
pub use faction::factions_page;
pub use get_rate_limit::get_rate_limit;
pub use market::market;
pub use navigate::navigate;
pub use orbit::orbit;
pub use purchase_ship::purchase_ship;
pub use query::Query;
pub use refuel::refuel;
pub use register::register;
pub use request_not_cloned_error::RequestNotClonedError;
pub use sell::sell;
pub use ship::ship;
pub use ship::ships;
pub use ship::ships_page;
pub use shipyard::shipyard;
pub use shipyard::shipyard_unauthorized;
pub use status::status;
pub use status_error::StatusError;
pub use system::system;
pub use system::systems;
pub use system::systems_page;
pub use too_many_retries_error::TooManyRetriesError;
pub use waypoint::waypoint;
pub use waypoint::waypoints;
pub use waypoint::waypoints_page;

pub const URL: &str = "https://api.spacetraders.io/v2";
pub const N_RETRIES: u16 = 5;
const MAX_LIMIT: u128 = 20;
