mod accept_contract;
mod agent;
mod contract;
mod contracts;
mod faction;
mod factions;
mod get_rate_limit;
mod register;
mod ship;
mod ships;
mod status;
mod status_error;
mod system;
mod systems;
mod too_many_retries_error;
mod waypoint;
mod waypoints;

pub use accept_contract::accept_contract;
pub use agent::agent;
pub use contract::contract;
pub use contracts::contracts;
pub use faction::faction;
pub use factions::factions;
use get_rate_limit::get_rate_limit;
pub use register::register;
pub use ship::ship;
pub use ships::ships;
pub use status::status;
pub use status_error::StatusError;
pub use system::system;
pub use systems::systems;
pub use too_many_retries_error::TooManyRetriesError;
pub use waypoint::waypoint;
pub use waypoints::waypoints;

pub const URL: &str = "https://api.spacetraders.io/v2";
const N_RETRIES: u16 = 5;
