mod find_delivery;
mod find_trade_good;
mod find_trait;
mod find_waypoint_type;
mod look_for_fuel;
mod look_for_market;
mod look_for_mine;
mod mine;
mod mining;
mod navigate_to_fuel;
mod navigate_to_market;
mod navigate_to_mine;
mod refuel_ship;
mod sell_cargo;
mod state;
mod trade_good_not_found_error;
mod trait_not_found_error;
mod try_refuel;
mod wait_until;
mod waypoint_type_not_found_error;

use find_delivery::find_delivery;
use find_trade_good::find_trade_good;
use find_trade_good::find_trade_good_in_system;
use find_trait::find_trait;
use find_trait::find_trait_in_system;
use find_waypoint_type::find_waypoint_type_in_system;
use look_for_fuel::look_for_fuel;
use look_for_market::look_for_market;
use look_for_mine::look_for_mine;
use mine::mine;
pub use mining::mining;
use navigate_to_fuel::navigate_to_fuel;
use navigate_to_market::navigate_to_market;
use navigate_to_mine::navigate_to_mine;
use refuel_ship::refuel_ship;
use sell_cargo::sell_cargo;
use state::State;
use trade_good_not_found_error::TradeGoodNotFoundError;
use trait_not_found_error::TraitNotFoundError;
use try_refuel::try_refuel;
use wait_until::wait_until;
use waypoint_type_not_found_error::WaypointTypeNotFoundError;

const MINING_WAYPOINT_TYPE: &str = "ASTEROID_FIELD";
const MARKET_TRAIT: &str = "MARKETPLACE";
const FUEL_SYMBOL: &str = "FUEL";
